Simple download...

diff --git a/bin/luaenv-rocks b/bin/luaenv-rocks
--- a/bin/luaenv-rocks
+++ b/bin/luaenv-rocks
@@ -9,38 +9,22 @@ if [ -z "${TARBALL_CACHE_PATH}" ] && [ -d "${LUAENV_ROOT}/cache" ]; then
   export TARBALL_CACHE_PATH="${LUAENV_ROOT}/cache"
 fi
 
-http() {
-  local method="$1"
-  local url="$2"
-  [ -n "$url" ] || return 1
+download() {
+  local url="$1"
+  local filename="$2"
+  [ -n "$url" ] || [ -n "$filename" ] || return 1
 
-  if type curl &>/dev/null; then
-    "http_${method}_curl" "$url"
+  if type aria2c &>/dev/null; then
+     aria2c -x5 -k1m -o "$filename" "$url"
+  elif type curl &>/dev/null; then
+    curl -o "$filename" "$url"
   elif type wget &>/dev/null; then
-    "http_${method}_wget" "$url"
+    wget -O "$filename" "$url"
   else
-    echo "error: please install \`curl\` or \`wget\` and try again" >&2
+    echo "error: please install \`aria2c\` or \`curl\` or \`wget\` and try again" >&2
     exit 1
   fi
 }
-
-
-http_head_curl() {
-  curl -qsILf "$1" >&4 2>&1
-}
-
-http_get_curl() {
-  curl -qsSLf "$1"
-}
-
-http_head_wget() {
-  wget -q --spider "$1" >&4 2>&1
-}
-
-http_get_wget() {
-  wget -nv -O- "$1"
-}
-
 
 fetch_tarball() {
   local package_name="$1"
@@ -174,4 +158,4 @@ main() {
 
 #main $1
 
-http get "http://luarocks.org/releases/luarocks-2.4.1.tar.gz" > "luarocks-2.4.1.tar.gz"
+download "https://keplerproject.github.io/luarocks/releases/luarocks-2.4.1.tar.gz" luarocks-2.4.1.tar.gz
