Cache downloaded tarballs.

diff --git a/bin/luaenv-rocks b/bin/luaenv-rocks
--- a/bin/luaenv-rocks
+++ b/bin/luaenv-rocks
@@ -13,31 +13,32 @@ download() {
   local url="$1"
   local filename="$2"
   [ -n "$url" ] || [ -n "$filename" ] || return 1
+  local cached_filename="$TARBALL_CACHE_PATH/$filename"
 
-  if type aria2c >/dev/null 2>&1; then
-     aria2c -x5 -k1m -o "$filename" "$url"
-  elif type curl >/dev/null 2>&1; then
-    curl -o "$filename" "$url"
-  elif type wget >/dev/null 2>&1; then
-    wget -O "$filename" "$url"
-  else
-    echo "error: please install \`aria2c\` or \`curl\` or \`wget\` and try again" >&2
-    exit 1
+   && return 0
+
+  if ![-e "$cached_filename"]; then
+    if type aria2c >/dev/null 2>&1; then
+      aria2c -x5 -k1m --summary-interval=0 -o "$cached_filename" "$url"
+    elif type curl >/dev/null 2>&1; then
+      curl -qsS -o "$cached_filename" "$url"
+    elif type wget >/dev/null 2>&1; then
+      wget -nv -O "$cached_filename" "$url"
+    else
+      echo "error: please install \`aria2c\` or \`curl\` or \`wget\` and try again" >&2
+      exit 1
+    fi
   fi
+  ln -s "$cached_filename" "$filename" >&4 2>&1 || return 1
 }
+
 
 fetch_tarball() {
   local package_name="$1"
   local package_url="$2"
-  #local signature_url="$1.asc"
 
   local package_filename="${package_name}.tar.gz"
-  #local signature_filename="${package_name}.tar.gz.asc"
-
-  symlink_tarball_from_cache "$package_filename" "$checksum" || {
-    echo "Downloading ${package_filename}..." >&2
-    download_tarball "$package_url" "$package_filename" "$checksum"
-  }
+  download "$package_url" "$package_filename"
 
   { tar xzvf "$package_filename"
     rm -f "$package_filename"
@@ -158,4 +159,4 @@ main() {
 
 #main $1
 
-download "https://keplerproject.github.io/luarocks/releases/luarocks-2.4.1.tar.gz" luarocks-2.4.1.tar.gz
+fetch_tarball "luarocks-2.4.1" "https://keplerproject.github.io/luarocks/releases/luarocks-2.4.1.tar.gz"
